### ISSUE TITLE
gpt4-0613一直报错

### ISSUE THREAD

**Issue by jaychoubaby** [hncboy/chatgpt-web-java#100]
10次偶尔有几次可以成功

![image](https://github.com/hncboy/chatgpt-web-java/assets/26641387/17a310c9-8e8d-4fc1-a5d1-e4bc30c09197)

**Comment by hncboy** [comment]
返回的信息写了速率限制

**Comment by jaychoubaby** [comment]
> 返回的信息写了速率限制



> 返回的信息写了速率限制

用sdk的测试类压测也没有出现速率限制的提示，但是走/chat_message/send 接口 偶尔可以成功，大部分都提示

{"role":null,"id":null,"parentMessageId":null,"conversationId":null,"text":"\n【接收消息处理异常，响应中断】"}

并且我已经把配置中的所有限制都去掉了，超时时间也调到了60秒

**Comment by hncboy** [comment]
gpt4 显示了每分钟 10000 tokens，目前的设计 maxTokens 取的是模型上限的最大 tokens 减去 promptTokens，gpt4 上限 8k。
猜测针对 tokens 速率限流时会包含 maxTokens，所以 1 分钟发送两次会导致 tokens 速率上限。

这块可以固定 maxTokens 的值。
