### ISSUE TITLE
本地无法启动项目，报错见图

### ISSUE THREAD

**Issue by 140619** [hncboy/chatgpt-web-java#104]
<img width="1166" alt="image" src="https://github.com/hncboy/chatgpt-web-java/assets/11607387/d0c9f4f1-093a-4e20-a598-e0dd64aa1e49">

环境：
电脑：MacBook m1
JDK17.42.19
MAVEN 3.8.6

错误信息如下：
/Users/XXX/.asdf/installs/java/zulu-17.42.19/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:50721,suspend=y,server=n -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=always -javaagent:/Users/G/Library/Caches/JetBrains/IntelliJIdea2021.3/captureAgent/debugger-agent.jar -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -Dfile.encoding=UTF-8 -classpath /Users/g/JavaProject/chatgpt-web-java/chatgpt-bootstrap/target/classes:/Users/g/.m2/repository/org/springframework/boot/spring-boot-starter-web/3.0.5/spring-boot-starter-web-3.0.5.jar:/Users/g/.m2/repository/org/springframework/boot/spring-boot-starter/3.0.5/spring-boot-starter-3.0.5.jar:/Users/g/.m2/repository/org/springframework/boot/spring-boot/3.0.5/spring-boot-3.0.5.jar:/Users/g/.m2/repository/org/springframework/boot/spring-boot-starter-logging/3.0.5/spring-boot-starter-logging-3.0.5.jar:/Users/g/.m2/repository/ch/qos/logback/logback-classic/1.4.6/logback-classic-1.4.6.jar:/Users/g/.m2/repository/ch/qos/logback/logback-core/1.4.6/logback-core-1.4.6.jar:/Users/g/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.19.0/log4j-to-slf4j-2.19.0.jar:/Users/g/.m2/repository/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar:/Users/g/.m2/repository/org/slf4j/jul-to-slf4j/2.0.7/jul-to-slf4j-2.0.7.jar:/Users/g/.m2/repository/jakarta/annotation/jakarta.annotation-api/2.1.1/jakarta.annotation-api-2.1.1.jar:/Users/g/.m2/repository/org/springframework/spring-core/6.0.7/spring-core-6.0.7.jar:/Users/g/.m2/repository/org/springframework/spring-jcl/6.0.7/spring-jcl-6.0.7.jar:/Users/g/.m2/repository/org/yaml/snakeyaml/1.33/snakeyaml-1.33.jar:/Users/g/.m2/repository/org/springframework/boot/spring-boot-starter-json/3.0.5/spring-boot-starter-json-3.0.5.jar:/Users/g/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.14.2/jackson-datatype-jdk8-2.14.2.jar:/Users/g/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.14.2/jackson-datatype-jsr310-2.14.2.jar:/Users/g/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.14.2/jackson-module-parameter-names-2.14.2.jar:/Users/g/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/3.0.5/spring-boot-starter-tomcat-3.0.5.jar:/Users/g/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/10.1.7/tomcat-embed-core-10.1.7.jar:/Users/g/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/10.1.7/tomcat-embed-websocket-10.1.7.jar:/Users/g/.m2/repository/org/springframework/spring-web/6.0.7/spring-web-6.0.7.jar:/Users/g/.m2/repository/org/springframework/spring-beans/6.0.7/spring-beans-6.0.7.jar:/Users/g/.m2/repository/io/micrometer/micrometer-observation/1.10.5/micrometer-observation-1.10.5.jar:/Users/g/.m2/repository/io/micrometer/micrometer-commons/1.10.5/micrometer-commons-1.10.5.jar:/Users/g/.m2/repository/org/springframework/spring-webmvc/6.0.7/spring-webmvc-6.0.7.jar:/Users/g/.m2/repository/org/springframework/spring-context/6.0.7/spring-context-6.0.7.jar:/Users/g/.m2/repository/org/springframework/spring-expression/6.0.7/spring-expression-6.0.7.jar:/Users/g/.m2/repository/org/springframework/boot/spring-boot-starter-validation/3.0.5/spring-boot-starter-validation-3.0.5.jar:/Users/g/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/10.1.7/tomcat-embed-el-10.1.7.jar:/Users/g/.m2/repository/org/hibernate/validator/hibernate-validator/8.0.0.Final/hibernate-validator-8.0.0.Final.jar:/Users/g/.m2/repository/jakarta/validation/jakarta.validation-api/3.0.2/jakarta.validation-api-3.0.2.jar:/Users/g/.m2/repository/org/jboss/logging/jboss-logging/3.5.0.Final/jboss-logging-3.5.0.Final.jar:/Users/g/.m2/repository/com/fasterxml/classmate/1.5.1/classmate-1.5.1.jar:/Users/g/.m2/repository/org/springframework/boot/spring-boot-starter-aop/3.0.5/spring-boot-starter-aop-3.0.5.jar:/Users/g/.m2/repository/org/springframework/spring-aop/6.0.7/spring-aop-6.0.7.jar:/Users/g/.m2/repository/org/aspectj/aspectjweaver/1.9.19/aspectjweaver-1.9.19.jar:/Users/g/.m2/repository/org/projectlombok/lombok/1.18.26/lombok-1.18.26.jar:/Users/g/.m2/repository/cn/hutool/hutool-all/5.8.15/hutool-all-5.8.15.jar:/Users/g/.m2/repository/com/unfbx/chatgpt-java/1.0.11/chatgpt-java-1.0.11.jar:/Users/g/.m2/repository/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar:/Users/g/.m2/repository/org/slf4j/slf4j-simple/2.0.7/slf4j-simple-2.0.7.jar:/Users/g/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.14.2/jackson-databind-2.14.2.jar:/Users/g/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.14.2/jackson-annotations-2.14.2.jar:/Users/g/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.14.2/jackson-core-2.14.2.jar:/Users/g/.m2/repository/com/squareup/okhttp3/okhttp-sse/4.10.0/okhttp-sse-4.10.0.jar:/Users/g/.m2/repository/com/squareup/okhttp3/okhttp/4.10.0/okhttp-4.10.0.jar:/Users/g/.m2/repository/com/squareup/okio/okio-jvm/3.0.0/okio-jvm-3.0.0.jar:/Users/g/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-common/1.7.22/kotlin-stdlib-common-1.7.22.jar:/Users/g/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.7.22/kotlin-stdlib-1.7.22.jar:/Users/g/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.7.22/kotlin-stdlib-jdk8-1.7.22.jar:/Users/g/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.7.22/kotlin-stdlib-jdk7-1.7.22.jar:/Users/g/.m2/repository/com/squareup/okhttp3/logging-interceptor/4.10.0/logging-interceptor-4.10.0.jar:/Users/g/.m2/repository/com/squareup/retrofit2/retrofit/2.9.0/retrofit-2.9.0.jar:/Users/g/.m2/repository/com/squareup/retrofit2/converter-jackson/2.9.0/converter-jackson-2.9.0.jar:/Users/g/.m2/repository/com/squareup/retrofit2/adapter-rxjava2/2.9.0/adapter-rxjava2-2.9.0.jar:/Users/g/.m2/repository/io/reactivex/rxjava2/rxjava/2.0.0/rxjava-2.0.0.jar:/Users/g/.m2/repository/org/reactivestreams/reactive-streams/1.0.4/reactive-streams-1.0.4.jar:/Users/g/.m2/repository/org/jetbrains/annotations/24.0.1/annotations-24.0.1.jar:/Users/g/.m2/repository/com/knuddels/jtokkit/0.1.0/jtokkit-0.1.0.jar:/Users/g/.m2/repository/org/springdoc/springdoc-openapi-starter-webmvc-ui/2.1.0/springdoc-openapi-starter-webmvc-ui-2.1.0.jar:/Users/g/.m2/repository/org/springdoc/springdoc-openapi-starter-webmvc-api/2.1.0/springdoc-openapi-starter-webmvc-api-2.1.0.jar:/Users/g/.m2/repository/org/springdoc/springdoc-openapi-starter-common/2.1.0/springdoc-openapi-starter-common-2.1.0.jar:/Users/g/.m2/repository/io/swagger/core/v3/swagger-core-jakarta/2.2.9/swagger-core-jakarta-2.2.9.jar:/Users/g/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar:/Users/g/.m2/repository/io/swagger/core/v3/swagger-annotations-jakarta/2.2.9/swagger-annotations-jakarta-2.2.9.jar:/Users/g/.m2/repository/io/swagger/core/v3/swagger-models-jakarta/2.2.9/swagger-models-jakarta-2.2.9.jar:/Users/g/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/4.0.0/jakarta.xml.bind-api-4.0.0.jar:/Users/g/.m2/repository/jakarta/activation/jakarta.activation-api/2.1.1/jakarta.activation-api-2.1.1.jar:/Users/g/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.14.2/jackson-dataformat-yaml-2.14.2.jar:/Users/g/.m2/repository/org/webjars/swagger-ui/4.18.2/swagger-ui-4.18.2.jar:/Users/g/.m2/repository/com/baomidou/mybatis-plus-boot-starter/3.5.3.1/mybatis-plus-boot-starter-3.5.3.1.jar:/Users/g/.m2/repository/com/baomidou/mybatis-plus/3.5.3.1/mybatis-plus-3.5.3.1.jar:/Users/g/.m2/repository/com/baomidou/mybatis-plus-extension/3.5.3.1/mybatis-plus-extension-3.5.3.1.jar:/Users/g/.m2/repository/com/baomidou/mybatis-plus-core/3.5.3.1/mybatis-plus-core-3.5.3.1.jar:/Users/g/.m2/repository/com/baomidou/mybatis-plus-annotation/3.5.3.1/mybatis-plus-annotation-3.5.3.1.jar:/Users/g/.m2/repository/com/github/jsqlparser/jsqlparser/4.4/jsqlparser-4.4.jar:/Users/g/.m2/repository/org/mybatis/mybatis/3.5.10/mybatis-3.5.10.jar:/Users/g/.m2/repository/org/mybatis/mybatis-spring/2.0.7/mybatis-spring-2.0.7.jar:/Users/g/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/3.0.5/spring-boot-autoconfigure-3.0.5.jar:/Users/g/.m2/repository/org/springframework/boot/spring-boot-starter-jdbc/3.0.5/spring-boot-starter-jdbc-3.0.5.jar:/Users/g/.m2/repository/com/zaxxer/HikariCP/5.0.1/HikariCP-5.0.1.jar:/Users/g/.m2/repository/org/springframework/spring-jdbc/6.0.7/spring-jdbc-6.0.7.jar:/Users/g/.m2/repository/org/springframework/spring-tx/6.0.7/spring-tx-6.0.7.jar:/Users/g/.m2/repository/org/mapstruct/mapstruct/1.5.3.Final/mapstruct-1.5.3.Final.jar:/Users/g/.m2/repository/com/mysql/mysql-connector-j/8.0.32/mysql-connector-j-8.0.32.jar:/Users/g/.m2/repository/cn/dev33/sa-token-spring-boot3-starter/1.34.0/sa-token-spring-boot3-starter-1.34.0.jar:/Users/g/.m2/repository/cn/dev33/sa-token-jakarta-servlet/1.34.0/sa-token-jakarta-servlet-1.34.0.jar:/Users/g/.m2/repository/jakarta/servlet/jakarta.servlet-api/6.0.0/jakarta.servlet-api-6.0.0.jar:/Users/g/.m2/repository/cn/dev33/sa-token-spring-boot-autoconfig/1.34.0/sa-token-spring-boot-autoconfig-1.34.0.jar:/Users/g/.m2/repository/cn/dev33/sa-token-jwt/1.34.0/sa-token-jwt-1.34.0.jar:/Users/g/.m2/repository/cn/dev33/sa-token-core/1.34.0/sa-token-core-1.34.0.jar:/Users/g/.m2/repository/cn/hutool/hutool-jwt/5.8.9/hutool-jwt-5.8.9.jar:/Users/g/.m2/repository/cn/hutool/hutool-json/5.8.9/hutool-json-5.8.9.jar:/Users/g/.m2/repository/cn/hutool/hutool-core/5.8.9/hutool-core-5.8.9.jar:/Users/g/.m2/repository/cn/hutool/hutool-crypto/5.8.9/hutool-crypto-5.8.9.jar:/Users/g/.m2/repository/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar:/Users/g/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/Users/g/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/Users/g/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/Users/g/.m2/repository/org/checkerframework/checker-qual/3.12.0/checker-qual-3.12.0.jar:/Users/g/.m2/repository/com/google/errorprone/error_prone_annotations/2.11.0/error_prone_annotations-2.11.0.jar:/Users/g/.m2/repository/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar:/Users/g/.m2/repository/javax/mail/javax.mail-api/1.6.2/javax.mail-api-1.6.2.jar:/Users/g/.m2/repository/com/sun/mail/javax.mail/1.6.2/javax.mail-1.6.2.jar:/Users/g/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar:/Users/g/.m2/repository/org/springframework/boot/spring-boot-starter-thymeleaf/3.0.5/spring-boot-starter-thymeleaf-3.0.5.jar:/Users/g/.m2/repository/org/thymeleaf/thymeleaf-spring6/3.1.1.RELEASE/thymeleaf-spring6-3.1.1.RELEASE.jar:/Users/g/.m2/repository/org/thymeleaf/thymeleaf/3.1.1.RELEASE/thymeleaf-3.1.1.RELEASE.jar:/Users/g/.m2/repository/org/attoparser/attoparser/2.0.6.RELEASE/attoparser-2.0.6.RELEASE.jar:/Users/g/.m2/repository/org/unbescape/unbescape/1.1.6.RELEASE/unbescape-1.1.6.RELEASE.jar:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar com.hncboy.chatgpt.ChatGptApplication
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Connected to the target VM, address: '127.0.0.1:50721', transport: 'socket'
错误: 找不到或无法加载主类 com.hncboy.chatgpt.ChatGptApplication
原因: java.lang.ClassNotFoundException: com.hncboy.chatgpt.ChatGptApplication
Disconnected from the target VM, address: '127.0.0.1:50721', transport: 'socket'

Process finished with exit code 1

**Comment by hncboy** [comment]
进入到对应启动类，然后点绿色启动箭头

**Comment by 140619** [comment]
> 进入到对应启动类，然后点绿色启动箭头

启动的com.hncboy.chatgpt.ChatGptApplication，出现的上面错误提示

**Comment by hncboy** [comment]
应该是你 IDEA 工具的问题吧。

> > 进入到对应启动类，然后点绿色启动箭头
> 
> 启动的com.hncboy.chatgpt.ChatGptApplication，出现的上面错误提示
