### ISSUE TITLE
数据库切换到mysql，添加登录功能 ，JWT 权限验证

### ISSUE THREAD

**Issue by AYZXX** [hncboy/chatgpt-web-java#12]

**Comment by AYZXX** [comment]
想问一下楼主，为什么不用mysql？

**Comment by hncboy** [comment]
> 想问一下楼主，为什么不用mysql？

已经支持 MySQL 了，改下连接地址就可以。

**Comment by AYZXX** [comment]
楼主， 这个地方如果 parentAnswerMessageId 为null 会有异常。
![image](https://user-images.githubusercontent.com/49258465/228720136-6ffd0bf3-5537-499a-8697-65f47bffd979.png)

**Comment by hncboy** [comment]
> 楼主， 这个地方如果 parentAnswerMessageId 为null 会有异常。 ![image](https://user-images.githubusercontent.com/49258465/228720136-6ffd0bf3-5537-499a-8697-65f47bffd979.png)

parentAnswerMessageId  为 null 应该直接 return 了。

**Comment by hncboy** [comment]
已解决
