### ISSUE TITLE
nginx反向代理问题

### ISSUE THREAD

**Issue by Mpynl** [hncboy/chatgpt-web-java#23]
使用nginx反向代理java api，前端在调用/api/session时出现404错误，而在用node启动项目时并未出现该错误，打包后的项目就会出现该错误

**Comment by hncboy** [comment]
咋配置的，nginx 反向代理 node 可以成功？

**Comment by Mpynl** [comment]
我是打包之后的静态代码，不是代理node

**Comment by hncboy** [comment]
我试了 nginx 代理 api 没问题。

**Comment by Mpynl** [comment]
这是我nginx的配置，你看一下有没有什么问题
![image](https://user-images.githubusercontent.com/42730048/229408971-0c4b3060-0627-4dd2-9e25-b6b668bb2f73.png)

**Comment by hncboy** [comment]
localhost 改为 ip

**Comment by XHXJ** [comment]
我也遇到了一样的问题
```
        location /api {
        # 处理 Node.js 后端 API 的请求
          proxy_pass http://127.0.0.1:3002/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Nginx-Proxy true;
          proxy_redirect off;
}
```
请求 URL: http://127.0.0.1:8089/api/session
请求方法: POST
状态代码: 404 Not Found
远程地址: 127.0.0.1:8089
引用者策略: strict-origin-when-cross-origin

提示404

**Comment by hncboy** [comment]
> 我也遇到了一样的问题
> 
> ```
>         location /api {
>         # 处理 Node.js 后端 API 的请求
>           proxy_pass http://127.0.0.1:3002/;
>           proxy_set_header Host $host;
>           proxy_set_header X-Real-IP $remote_addr;
>            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>           proxy_set_header X-Nginx-Proxy true;
>           proxy_redirect off;
> }
> ```
> 
> 请求 URL: http://127.0.0.1:8089/api/session 请求方法: POST 状态代码: 404 Not Found 远程地址: 127.0.0.1:8089 引用者策略: strict-origin-when-cross-origin
> 
> 提示404

127.0.0.1 改到其他网卡 ip

**Comment by XHXJ** [comment]
```

server {
	listen 8089;
	server_name  localhost;
	charset utf-8;
	error_page   500 502 503 504  /50x.html;
	location / {
            root   html;
   		    try_files $uri /index.html;
	}

	location /api {
			proxy_set_header   X-Real-IP $remote_addr; #转发用户IP
			proxy_pass http://192.168.0.18:3002;
	}

	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header REMOTE-HOST $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```
不行都改了好多了

**Comment by mornone** [comment]
错误：`location /api`
正确：`location /api/`
经测试api前后均需要加斜杠
