### ISSUE TITLE
使用BT时的docker安装时，提示连不上数据库

### ISSUE THREAD

**Issue by sygaton** [hncboy/chatgpt-web-java#24]
[问题描述]
1. 根据README的脚本命令安装了mysql，且启动成功，如下图所示：
<img width="747" alt="image" src="https://user-images.githubusercontent.com/26806498/229784156-98900d04-abaa-4d4a-9862-ed11d2be5c32.png">

2.  修改[docker-compose.yml](https://github.com/hncboy/chatgpt-web-java/blob/main/docker-compose.yml)文件，采用
```bash
docker-compose up -d
```
命令启动后，启动报错，提示连不上数据库，请问这个IP地址是采用localhost，还有哪个地址？

**Comment by hncboy** [comment]
试试用新的 docker-compose，MySQL 和 Java 一起装。
