### ISSUE TITLE
能介绍下限流功能的详细使用规则么，我看配置参数有5项

### ISSUE THREAD

**Issue by sygaton** [hncboy/chatgpt-web-java#26]
## [问题描述] 请介绍下限流功能的详细使用规则

```bash
  # 全局时间内最大请求次数
  maxRequest: 60
  # 全局最大请求时间间隔（秒）
  maxRequestSecond: 1800
  # ip 时间内最大请求次数
  ipMaxRequest: 5
  # ip 最大请求时间间隔（秒）
  ipMaxRequestSecond: 3600
  # 限制上下文对话的数量
  limitQuestionContextCount: 3
```

以上几项的限流规则，全局、IP和限制上下文的对话数量是什么关系，谢谢。

**Comment by hncboy** [comment]
1.上下文对话数量和限流没关系

2.限流的时间就是一段时间，比如 1800 秒，就是针对 30 分钟内的请求进行限流，目前限流采用的是滑动窗口算法。次数指的是 30 分钟内能发多少次，比如次数是 60。表示 30 分钟内只能发送 60 条消息。openai 接口本身也有作限流处理。这块限流功能如果是容器部署的话，限流记录重启会丢失。
全局限流就是针对所有用户的，ip 限流就是针对某个 ip。任意一个限流条件被触发就会被限制发送消息。

3.上下文对话数量表示与之前对话的关联关系，是否是连续的。3 表示在同一个上下文内最多只能连续提问三次，会记忆上次的对话内容。这个数量越大消耗的 tokens 会越多。
