### ISSUE TITLE
nginx代理时流式输出的问题

### ISSUE THREAD

**Issue by limi1** [hncboy/chatgpt-web-java#29]
修改nginx配置信息即可实现流式输出。
Java后台已经实现了流式输出，数据到nginx 的时候进行了一次缓存，这时就需要关闭nginx的缓冲流。
如下：
http{
    server{
       xxxx   xxx;
       proxy_buffering off;
       xxx xxxx;
    }
}

**Comment by hncboy** [comment]
感谢。
