### ISSUE TITLE
使用最新的ChatGpt-web调用聊天功能没有反应

### ISSUE THREAD

**Issue by TSiven** [hncboy/chatgpt-web-java#3]
1. web授权没有弹出来
2. 发送聊天, java控制台有打印内容, 前端返回没有输出

**Comment by TSiven** [comment]
使用的jdk8, web下载的最新版本, 跟jdk有关系吗

**Comment by TSiven** [comment]
<img width="1441" alt="image" src="https://user-images.githubusercontent.com/31428470/227755861-e979a881-c31d-4ba5-aed4-ac0bb1a3aabc.png">

<img width="956" alt="image" src="https://user-images.githubusercontent.com/31428470/227755877-6c08a619-5c15-4c69-93a0-d2e22a7bb278.png">

**Comment by TSiven** [comment]
找到问题了, 消息解析返回了null

com.qksmart.service.api.parser.ChatCompletionResponseParser

 @Override
    public ChatReplyMessageVO parseChatReplyMessageVO(String receivedMessage, String originalData) {
        Message message = getMessage(originalData);
        if (Objects.isNull(message)) {
            return null;
        }
        ChatReplyMessageVO chatReplyMessageVO = new ChatReplyMessageVO();
        chatReplyMessageVO.setRole(message.getRole());
        chatReplyMessageVO.setText(receivedMessage);

        return chatReplyMessageVO;
    }

**Comment by hncboy** [comment]
> 找到问题了, 消息解析返回了null <img alt="image" width="1022" src="https://user-images.githubusercontent.com/31428470/227756813-7fba90ed-33c2-45bc-bb3d-70902425855f.png">
> 
> com.qksmart.service.api.parser.ChatCompletionResponseParser
> 
> @OverRide public ChatReplyMessageVO parseChatReplyMessageVO(String receivedMessage, String originalData) { Message message = getMessage(originalData); if (Objects.isNull(message)) { return null; } ChatReplyMessageVO chatReplyMessageVO = new ChatReplyMessageVO(); chatReplyMessageVO.setRole(message.getRole()); chatReplyMessageVO.setText(receivedMessage);
> 
> ```
>     return chatReplyMessageVO;
> }
> ```

这块正在引入新的功能，这个已经修复了，待会儿提下。

**Comment by hncboy** [comment]
试试这一版

**Comment by hncboy** [comment]
已解决。
