### ISSUE TITLE
目前不支持连续对话

### ISSUE THREAD

**Issue by TSiven** [hncboy/chatgpt-web-java#4]
目前消息不支持连续对话

**Comment by hncboy** [comment]
我这边试了是可以连续对话的，会把之前的上下文传过去。你是怎么尝试的。

**Comment by TSiven** [comment]
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/31428470/227760872-9343ba14-f34c-4b16-97a1-010212764aa0.png">

看源代码, 构建request请求的时候,用户消息只有当前的消息内容 .messages(Arrays.asList(systemMessage, userMessage)), 没有上下文的消息呀

**Comment by TSiven** [comment]
啊哦, 原来刚刚提交了一版系你的代码, 我代码是旧的了..  更新新代码看到最新代码有添加上下文问题消息的内容.

**Comment by TSiven** [comment]
另外一个问题是 ApiModelVO的hasAuth参数, 需要改成auth, 前端是通过这个参数控制鉴权判断的

**Comment by hncboy** [comment]
> 另外一个问题是 ApiModelVO的hasAuth参数, 需要改成auth, 前端是通过这个参数控制鉴权判断的

好的。
