### ISSUE TITLE
大佬，什么时候对接azure openai

### ISSUE THREAD

**Issue by itxtl** [hncboy/chatgpt-web-java#40]
如题，大佬，什么时候对接azure openai

**Comment by hncboy** [comment]
还不知道，后期再看看。

**Comment by q1139168548** [comment]
参考这个项目https://github.com/diemus/azure-openai-proxy

**Comment by zzy-life** [comment]
https://github.com/TheoKanning/openai-java/pull/259/files
什么时候更新支持一下

**Comment by hncboy** [comment]
> https://github.com/TheoKanning/openai-java/pull/259/files 什么时候更新支持一下

下个版本可以参考下

**Comment by hncboy** [comment]
https://github.com/haibbo/cf-openai-azure-proxy 这个项目应该可以支持切换 azure，无需改动代码。
