### ISSUE TITLE
大佬，前端参考步骤构建执行报错

### ISSUE THREAD

**Issue by itxtl** [hncboy/chatgpt-web-java#41]
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/28883383/231030358-f86614e9-5267-4e5d-8213-a29aac9ec491.png">
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/28883383/231030367-ee9516f3-18cb-43bb-a2d7-e5260b9672ac.png">

**Comment by hncboy** [comment]
已解决，关联 https://github.com/mjjh1717/chatgpt-shuowen/issues/2
