### ISSUE TITLE
最新代码，charroom加了user_id但是没有给值，违反非空约束

### ISSUE THREAD

**Issue by butnows** [hncboy/chatgpt-web-java#47]
@Service("FrontChatRoomServiceImpl")
public class ChatRoomServiceImpl extends ServiceImpl<ChatRoomMapper, ChatRoomDO> implements ChatRoomService {

    @Override
    public ChatRoomDO createChatRoom(ChatMessageDO chatMessageDO) {
        ChatRoomDO chatRoom = new ChatRoomDO();
        chatRoom.setId(IdWorker.getId());
        chatRoom.setApiType(chatMessageDO.getApiType());
        chatRoom.setIp(WebUtil.getIp());
        chatRoom.setFirstChatMessageId(chatMessageDO.getId());
        chatRoom.setFirstMessageId(chatMessageDO.getMessageId());
        // 取一部分内容当标题
        chatRoom.setTitle(StrUtil.sub(chatMessageDO.getContent(), 0, 50));
        chatRoom.setCreateTime(new Date());
        chatRoom.setUpdateTime(new Date());
        save(chatRoom);
        return chatRoom;
    }
}

但是你们的测试环境没有报错不知道为什么

**Comment by hncboy** [comment]
忘记加了。

**Comment by butnows** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
