### ISSUE TITLE
请求携带的token长度是不是异常了，输入什么响应都是超长了

### ISSUE THREAD

**Issue by butnows** [hncboy/chatgpt-web-java#50]
"error": {
    "message": "This model's maximum context length is 8192 tokens. However, you requested 8192 tokens (58 in the messages, 8134 in the completion). Please reduce the length of the messages or completion.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }

**Comment by hncboy** [comment]
是最新的代码吗，这块计算调整下了。GPT3.5 测试是正常。GPT-4 没测试过，看下表中 promptTokens 值是多少

**Comment by hncboy** [comment]
那应该还要再减一

**Comment by butnows** [comment]
是的，减一可以解决

**Comment by hncboy** [comment]
代码里已减一。
