### ISSUE TITLE
使用第三方代理地址，ChatGPT已返回信息，但系统报错

### ISSUE THREAD

**Issue by aohun** [hncboy/chatgpt-web-java#51]
![image](https://user-images.githubusercontent.com/37433539/233520030-04e9a1a3-cbea-45d9-aa8a-a0d2e4f9b4a1.png)
![image](https://user-images.githubusercontent.com/37433539/233520201-92f5ea09-4d20-41a2-9dc4-251a1f15cc01.png)
![image](https://user-images.githubusercontent.com/37433539/233524991-5faa5df1-dfbc-4bc4-b210-9ec12da51575.png)
最后这个data的done不知道从哪来的。

**Comment by hncboy** [comment]
[DONE] 是正常返回

**Comment by hncboy** [comment]
> ParsedEventSourceAzureListener isEnd=true 的业务逻辑，是不是可以放到onClosed去处理,, 更简单一些？ 应该和在onEvent中使用 "[DONE]" 标记处理业务是等价的吧？

不一样的。收到 [DONE] 还没有 closed
