### ISSUE TITLE
配置后端域名

### ISSUE THREAD

**Issue by maozhongsheng** [hncboy/chatgpt-web-java#61]
![image](https://user-images.githubusercontent.com/67531389/236103060-fdc20d8d-c17b-4054-bb37-5f9fc68c988b.png)
根据git上提供的第一种方法没有生效

**Comment by hncboy** [comment]
这是 vercel 部署的方式，没弄错吧

**Comment by maozhongsheng** [comment]
> 这是 vercel 部分的方式，没有弄错吧

因为我这边不是太会前端，如果我需要打包部署到服务器上面，如何修改访问后端的域名呢

**Comment by hncboy** [comment]
> 

nginx

**Comment by lovewe** [comment]
> > 这是 vercel 部分的方式，没有弄错吧
> 
> 因为我这边不是太会前端，如果我需要打包部署到服务器上面，如何修改访问后端的域名呢

请问你弄好了吗？

**Comment by maozhongsheng** [comment]
> > 
> 
> nginx

nginx 我配置好了前端和后端域名，我的意思是我如何在这套代码里面配置我nginx配置的后端域名不然访问不到

**Comment by hncboy** [comment]
> > > 
> > 
> > 
> > nginx
> 
> nginx 我配置好了前端和后端域名，我的意思是我如何在这套代码里面配置我nginx配置的后端域名不然访问不到

nginx 就被配下 shuowen 和 jiezi 的 api 接口 和 api/admin 接口i代理。

**Comment by maozhongsheng** [comment]
> > > > 
> > > 
> > > 
> > > nginx
> > 
> > 
> > nginx 我配置好了前端和后端域名，我的意思是我如何在这套代码里面配置我nginx配置的后端域名不然访问不到
> 
> nginx 就被配下 shuowen 和 jiezi 的 api 接口 和 api/admin 接口i代理。

这些接口和前端域名我都代理好了，我现在的问题是在vue代码中如何绑定已经代理好的后端域名在vue代码的哪里设置

**Comment by hncboy** [comment]
> > > > > 
> > > > 
> > > > 
> > > > nginx
> > > 
> > > 
> > > nginx 我配置好了前端和后端域名，我的意思是我如何在这套代码里面配置我nginx配置的后端域名不然访问不到
> > 
> > 
> > nginx 就被配下 shuowen 和 jiezi 的 api 接口 和 api/admin 接口i代理。
> 
> 这些接口和前端域名我都代理好了，我现在的问题是在vue代码中如何绑定已经代理好的后端域名在vue代码的哪里设置

vue 代码都不需要动，nginx 配好就行了。

**Comment by maozhongsheng** [comment]
> 

> > > > > > 
> > > > > 
> > > > > 
> > > > > nginx
> > > > 
> > > > 
> > > > nginx 我配置好了前端和后端域名，我的意思是我如何在这套代码里面配置我nginx配置的后端域名不然访问不到
> > > 
> > > 
> > > nginx 就被配下 shuowen 和 jiezi 的 api 接口 和 api/admin 接口i代理。
> > 
> > 
> > 这些接口和前端域名我都代理好了，我现在的问题是在vue代码中如何绑定已经代理好的后端域名在vue代码的哪里设置
> 
> vue 代码都不需要动，nginx 配好就行了。

好的我试下

**Comment by q1139168548** [comment]
楼主配好了吗，可以看下nginx配置吗

**Comment by hncboy** [comment]
> 楼主配好了吗，可以看下nginx配置吗

#71
