### ISSUE TITLE
我本地启动之后两个用户访问，就不能正常使用了，是每个用户都需要配置一个apikey吗？

### ISSUE THREAD

**Issue by square-box** [hncboy/chatgpt-web-java#65]
我本地启动之后两个用户访问，就不能正常使用了，是每个用户都需要配置一个apikey吗？

辛苦大佬帮忙解答

**Comment by hncboy** [comment]
不能正常使用是什么意思，再开一个无痕窗口试试。

**Comment by square-box** [comment]
就是我在本地启动了项目之后，然后在局域网内另一个同事，访问了我这个项目，我本地再请求chatgpt的时候就没有反应了

**Comment by square-box** [comment]
跟多用户多api key有关系吗

**Comment by hncboy** [comment]
> 跟多用户多api key有关系吗

没遇到过这个问题，项目本身是多用户，多 apiKey 的话目前不支持，但是和请求 chatgpt 接口关系不大。

**Comment by square-box** [comment]
我知道什么原因了，我把本地电脑做了一个公网映射给同事，这个比较慢。

大佬，你那个测试网址是购买的国外的服务器吗？

**Comment by hncboy** [comment]
> 我知道什么原因了，我把本地电脑做了一个公网映射给同事，这个比较慢。
> 
> 大佬，你那个测试网址是购买的国外的服务器吗？

是的
