### ISSUE TITLE
AccessToken 方式怎么使用？

### ISSUE THREAD

**Issue by lkj7b226** [hncboy/chatgpt-web-java#66]
参数api_reverse_proxy 配置的 https://chat.openai.com/backend-api/conversation，accessToken 是在https://chat.openai.com/ 页面从浏览器拿的。 现在是不是不能用这种方式，我试了调用接口不通，我看其他一些项目，还要配置cookie

**Comment by hncboy** [comment]
api_reverse_proxy 不能直接配 https://chat.openai.com/backend-api/conversation，搭建代理服务的方式参考 https://github.com/linweiyuan/go-chatgpt-api

**Comment by lkj7b226** [comment]
> api_reverse_proxy 不能直接配 [https://chat.openai.com/backend-api/conversation，搭建代理服务的方式参考](https://chat.openai.com/backend-api/conversation%EF%BC%8C%E6%90%AD%E5%BB%BA%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1%E7%9A%84%E6%96%B9%E5%BC%8F%E5%8F%82%E8%80%83) https://github.com/linweiyuan/go-chatgpt-api
我本地开了VPN，可以访问chatGPT，然后修改了accessToken 方式的请求源码，和api-Key 一样请求的时候加了代理，使用vpn的代理端口，这种方式也不行吗？必须要搭建代理服务才可以吗

**Comment by hncboy** [comment]
不行的，AccessToken 需要绕过 CloudFlare 验证。

**Comment by LYXCQX** [comment]
> api_reverse_proxy 不能直接配 [https://chat.openai.com/backend-api/conversation，搭建代理服务的方式参考](https://chat.openai.com/backend-api/conversation%EF%BC%8C%E6%90%AD%E5%BB%BA%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1%E7%9A%84%E6%96%B9%E5%BC%8F%E5%8F%82%E8%80%83) https://github.com/linweiyuan/go-chatgpt-api

搭建了代理服务器后将，apiReverseProxy 设置成自己的代理服务器地址就可以了么，还需要什么配置

**Comment by hncboy** [comment]
> > api_reverse_proxy 不能直接配 [https://chat.openai.com/backend-api/conversation，搭建代理服务的方式参考](https://chat.openai.com/backend-api/conversation%EF%BC%8C%E6%90%AD%E5%BB%BA%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1%E7%9A%84%E6%96%B9%E5%BC%8F%E5%8F%82%E8%80%83) https://github.com/linweiyuan/go-chatgpt-api
> 
> 搭建了代理服务器后将，apiReverseProxy 设置成自己的代理服务器地址就可以了么，还需要什么配置

然后再配上自己的 accesstoken 就可以了。
