### ISSUE TITLE
请问front2.stargpt.top这个用的是哪个模型？

### ISSUE THREAD

**Issue by lovewe** [hncboy/chatgpt-web-java#67]
我本地跑起来之后，感觉没有front2.stargpt.top这个智能，请问front2.stargpt.top用的是哪个模型？怎么更换成和front2.stargpt.top一样的

**Comment by hncboy** [comment]
默认的模型，gpt-3.5-turbo

**Comment by lovewe** [comment]
> 默认的模型，gpt-3.5-turbo

那模型是和API KEY绑定的吗？我本地启动的用我自己的API KEY，就没有front2.stargpt.top智能

**Comment by hncboy** [comment]
> > 默认的模型，gpt-3.5-turbo
> 
> 那模型是和API KEY绑定的吗？我本地启动的用我自己的API KEY，就没有front2.stargpt.top智能

模型是在代码里指定的，默认走 gpt-3.5-turbo。可能是回答内容不一样，并不是不智能。

**Comment by lovewe** [comment]
> > > 默认的模型，gpt-3.5-turbo
> > 
> > 
> > 那模型是和API KEY绑定的吗？我本地启动的用我自己的API KEY，就没有front2.stargpt.top智能
> 
> 模型是在代码里指定的，默认走 gpt-3.5-turbo。可能是回答内容不一样，并不是不智能。

我问现在北京时间是多少，我本地的回答是 “抱歉，作为一名AI助手，我没有实时的钟表功能，无法提供当前的北京时间。请您自行查询或参考其他来源获取准确的时间信息”。front2.stargpt.top这个就能正确回答出当前时间。

**Comment by hncboy** [comment]
> 

看运气，演示网站也回答不出来。你问今天是几号是可以回答的，因为把今天的日期当作上下文传过去了。

**Comment by lovewe** [comment]
> > 
> 
> 看运气，演示网站也回答不出来。你问今天是几号是可以回答的，因为把今天的日期当作上下文传过去了。

嗯嗯，谢谢大佬
