### ISSUE TITLE
本地启动的，回答的答案是等了一会一下全部展示，而不是一个字一个字的展示

### ISSUE THREAD

**Issue by lovewe** [hncboy/chatgpt-web-java#68]
如题，请问是有什么配置吗？还是什么原因导致的啊

**Comment by hncboy** [comment]
本地没遇到过这种情况，nginx 会出现。

**Comment by lovewe** [comment]
> 

我是在本地用nginx启动的，请求是什么原因啊？该怎么解决呢？

**Comment by lovewe** [comment]
> 本地没遇到过这种情况，nginx 会出现。

我是在本地用nginx启动的，请求是什么原因啊？该怎么解决呢？

**Comment by hncboy** [comment]
ngxin 配置中添加 proxy_buffering off;

**Comment by lovewe** [comment]
> ngxin 配置中添加 proxy_buffering off;

`server {
  listen 80;
  server_name _;
  proxy_buffering off;
  access_log /var/log/nginx/access.log  combined;
  gzip  on;
  gzip_comp_level 5;
  gzip_types text/plain application/javascript application/x-javascript text/javascript text/xml text/css;
  index index.html index.htm index.jsp index.php;
  location / {
    proxy_pass http://127.0.0.1:8080; 
    add_header Access-Control-Allow-Origin *;
    proxy_set_header  Host $host;
    proxy_set_header  X-real-ip $remote_addr;
    proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}`

大佬，我是这样配置的，不起作用啊

**Comment by hncboy** [comment]
你确定是这样配的，我咋觉得你的 nginx 配错了，没有代理 /api/。你本地启动 nginx，然后本地访问地址，nginx 不是用在本地的。

**Comment by lovewe** [comment]
> 你确定是这样配的，我咋觉得你的 nginx 配错了，没有代理 /api/。你本地启动 nginx，然后本地访问地址，nginx 不是用在本地的。

嗯嗯，这个是代理的前端地址，配置到后端地址的nginx server块中就可以了，谢谢大佬
