### ISSUE TITLE
关联上下文有问题

### ISSUE THREAD

**Issue by ibalbal** [hncboy/chatgpt-web-java#7]
会把之前的问题重新回答一边
![image](https://user-images.githubusercontent.com/63410603/228174344-4fa2455a-3881-47e2-b6a4-df1be88160df.png)

**Comment by hncboy** [comment]
实现方式应该出了问题，我排查下。

**Comment by hncboy** [comment]
已经修复，之前的上下文对话只传了用户的回答，没有传 gpt 的回答。
