### ISSUE TITLE
大佬能参考一下您的nginx配置吗？我这边一直出问题

### ISSUE THREAD

**Issue by shizhanghongchen** [hncboy/chatgpt-web-java#71]
> 你确定是这样配的，我咋觉得你的 nginx 配错了，没有代理 /api/。你本地启动 nginx，然后本地访问地址，nginx 不是用在本地的。

嗯嗯，这个是代理的前端地址，配置到后端地址的nginx server块中就可以了，谢谢大佬

_Originally posted by @lovewe in https://github.com/hncboy/chatgpt-web-java/issues/68#issuecomment-1539453441_

**Comment by hncboy** [comment]
# 说文配置
    server {
        listen 1002;
        server_name _;
        index index.html;
        proxy_buffering off;
        root /usr/local/chatgpt/chatgpt-shuowen/dist;

        #引用反向代理规则，注释后配置的反向代理将无效
        location /api/ {
            proxy_pass http://localhost:3005/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            add_header X-Cache $upstream_cache_status;
        }

        #禁止访问的文件或目录
        location ~ ^/(\.user.ini|\.htaccess|\.git|\.env|\.svn|\.project|LICENSE|README.md) {
            return 404;
        }
    }

    # 解字配置
    server {
        listen 3200;
        server_name _;
        index index.html;
        root /usr/local/chatgpt/chatgpt-jiezi/dist;

        #引用反向代理规则，注释后配置的反向代理将无效
        location /api/ {
            proxy_pass http://localhost:3005/admin/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            add_header X-Cache $upstream_cache_status;
        }

        #禁止访问的文件或目录
        location ~ ^/(\.user.ini|\.htaccess|\.git|\.env|\.svn|\.project|LICENSE|README.md) {
            return 404;
        }
    }
