### ISSUE TITLE
敏感词导入问题

### ISSUE THREAD

**Issue by shizhanghongchen** [hncboy/chatgpt-web-java#75]
1.根据README文档介绍新建sensitive_word_base64.txt文件如图所示：
<img width="863" alt="image" src="https://github.com/hncboy/chatgpt-web-java/assets/28671142/bd5eaf56-cad3-4082-a78e-4308c4b28cd2">
2. 敏感词文件路径/chatgpt-bootstrap/src/main/resources/sensitive_word_base64.txt，如下图所示：
<img width="312" alt="image" src="https://github.com/hncboy/chatgpt-web-java/assets/28671142/5b279b26-27db-4676-97dd-f66996f0940e">
3. 项目启动后敏感词信息并未加载到数据库，工程代码中也未找到相关路径配置请问是不是我哪里操作不对？辛苦有知道的大神解答一下谢谢！

**Comment by zzy-life** [comment]
直接进数据库用sql导入就行了

**Comment by hncboy** [comment]
> 1.根据README文档介绍新建sensitive_word_base64.txt文件如图所示： <img alt="image" width="863" src="https://user-images.githubusercontent.com/28671142/238175602-bd5eaf56-cad3-4082-a78e-4308c4b28cd2.png"> 2. 敏感词文件路径/chatgpt-bootstrap/src/main/resources/sensitive_word_base64.txt，如下图所示： <img alt="image" width="312" src="https://user-images.githubusercontent.com/28671142/238175624-5b279b26-27db-4676-97dd-f66996f0940e.png"> 3. 项目启动后敏感词信息并未加载到数据库，工程代码中也未找到相关路径配置请问是不是我哪里操作不对？辛苦有知道的大神解答一下谢谢！

这个功能移除了，README 没有更新，从数据库导入吧。

**Comment by shizhanghongchen** [comment]
好的
