### ISSUE TITLE
{ “错误”： { “消息”： “”， “类型”： “invalid_request_error”， “参数”： null，   “代码”：  “invalid_api_key” }

### ISSUE THREAD

**Issue by liu-Y-p** [hncboy/chatgpt-web-java#83]
2023-06-16T16:44:24.851+08:00  WARN 87648 --- [ncentcs.com/...] c.h.c.f.a.l.ParsedEventSourceListener    : 消息发送异常，当前已接收消息：，响应内容：{
    "error": {
        "message": "",
        "type": "invalid_request_error",
        "param": null,
        "code": "invalid_api_key"
    }
}
，异常堆栈：

**Comment by hncboy** [comment]
apiKey 是错的，确认下 apiKey。如果是 accessToken 模式，不需要填写 apiKey
