### ISSUE TITLE
vpn挂着，浏览器可正常访问chatgpt,工程跑的时候一直报 Failed to connect to api.openai.com/[2a03:2880:f10d:83:face:b00c:0:25de]:443

### ISSUE THREAD

**Issue by dexterrrrrcc** [hncboy/chatgpt-web-java#85]

**Comment by dexterrrrrcc** [comment]
![image](https://github.com/hncboy/chatgpt-web-java/assets/58161539/147c02e9-6a5e-47a2-991a-2888af92ea45)

**Comment by hncboy** [comment]
IDEA 运行的代码不会通过系统代理，项目内置了代理参数，http_proxy_host 和 http_proxy_port，需要自己填写下 port，参数含义见 https://github.com/hncboy/chatgpt-web-java/wiki/%E6%A8%A1%E5%BC%8F%E5%8F%82%E6%95%B0%E4%BB%8B%E7%BB%8D
