### ISSUE TITLE
新建的子模块不会被编译怎么办?

### ISSUE THREAD

**Issue by 2581218163** [hncboy/chatgpt-web-java#86]
我在项目中新增了一个子模块,但是启动的时候这个子模块并不会被编译。

**Comment by 2581218163** [comment]
![205df31b766b50e65d67eddfe836864](https://github.com/hncboy/chatgpt-web-java/assets/45324237/1e078571-53d7-44da-8f38-6d47325be7bf)
![e6e9cfc95c5451da51df6443cf18e2e](https://github.com/hncboy/chatgpt-web-java/assets/45324237/f5fefc5a-8d4e-4ec5-93ef-287efe7eb778)

**Comment by hncboy** [comment]
boostrap 的 pom 放入这个模块的依赖。
