### ISSUE TITLE
请教一个问题哈，用nginx部署后，调用后端api,好像没有通过流的方式来返回数据，而是整体返回的，并且等待的时间较长，大家有碰到这个问题吗？

### ISSUE THREAD

**Issue by yuanqs** [hncboy/chatgpt-web-java#92]
location / {
        root xxxx.com;
        index index.html index.htm;
    }
  # 移除 /api/
    location ^~/api/ {
       client_max_body_size 20m;
       proxy_pass http://127.0.0.1:3002/;
       proxy_set_header Host $host;
       proxy_set_header X-Forwarded-Host $server_name;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

**Comment by hncboy** [comment]
#71

**Comment by yuanqs** [comment]
> 

谢谢大佬，已经搞定了☺
