### ISSUE TITLE
大佬们。你们网络代理咋弄得，我实体机里代理了，怎么给docker容器里的代理

### ISSUE THREAD

**Issue by zhsaa** [hncboy/chatgpt-web-java#93]

**Comment by hncboy** [comment]
和宿主机同个网络，应该可以直连 openai，不需要再填代理地址吧。

**Comment by zhsaa** [comment]
> 和宿主机同个网络，应该可以直连 openai，不需要再填代理地址吧。
![image](https://github.com/hncboy/chatgpt-web-java/assets/137663220/6af5a8ce-3bf2-4398-99ad-98268565ba0b)
这个位置是这么填吗?

**Comment by hncboy** [comment]
curl https://api.openai.com/  先试试能不能通
