### ISSUE TITLE
注册提交请求后 无法收到邮箱

### ISSUE THREAD

**Issue by wjcaozhi** [hncboy/chatgpt-web-java#95]
邮箱信息已经配置，但是无法发送邮箱、
邮箱信息是正确的，自己做了一个test 可以正常发送邮件

**Comment by hncboy** [comment]
看下数据库邮件发送日志表的记录

**Comment by wjcaozhi** [comment]
数据库中是有发送记录的

**Comment by hncboy** [comment]
> 数据库中是有发送记录的

看下数据库的发送记录状态是否是成功的。如果成功的话，看看发件方的已发送里是否有记录。
