### ISSUE TITLE
集成redis后 使用application.yaml无法读取到配置

### ISSUE THREAD

**Issue by xiaoshandegithub** [hncboy/chatgpt-web-java#96]
集成spring-boot-starter-data-redis后 使用application.yaml无法读取到配置， 使用application.properties 后就可以正常使用了，这个是什么原因啊？

**Comment by hncboy** [comment]
我这没问题。

**Comment by xiaoshandegithub** [comment]
看下你的配置

**Comment by hncboy** [comment]
> 看下你的配置

项目目前没有集成 Redis。新版本集成了，自己遇到问题先自己解决下。

**Comment by xiaoshandegithub** [comment]
配置文件后缀修改为 .yml 就可以了
