### ISSUE TITLE
是否需要在服务器上配置vpn

### ISSUE THREAD

**Issue by wjcaozhi** [hncboy/chatgpt-web-java#97]
Cannot read properties of undefined (reading 'status')  
总是提示我这个异常

**Comment by hncboy** [comment]
api.openai.com 需要国外服务网才能直连。也可以通过 cloudflare 搭建免费的代理转发 https://github.com/barretlee/cloudflare-proxy

> Cannot read properties of undefined (reading 'status') 总是提示我这个异常
