### ISSUE TITLE
服务启动一段时间就报链接问题，但不影响运行

### ISSUE THREAD

**Issue by xiaoshandegithub** [hncboy/chatgpt-web-java#99]
HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@62a273ab (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER_NAME:}
    password: ${MYSQL_PASSWORD:}
    url: ${JDBC_URL:jdbc:mysql:}
# 增加了如下参数
    hikari:
      max-lifetime: 1200000

 增加了如上参数也还是存在问题，不知道大家有没有遇到？

**Comment by hncboy** [comment]
没遇到过这种情况

**Comment by xiaoshandegithub** [comment]
发现链接我本地的mysql就没有问题，链接远程服务器的就会出现
